# Generated by Django 4.1.1 on 2022-09-23 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(default='xyz', max_length=254),
        ),
        migrations.AddField(
            model_name='profile',
            name='pw',
            field=models.CharField(default='djangotest', max_length=16),
        ),
    ]
