# Generated by Django 4.1.1 on 2022-09-23 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_alter_profile_pp_alter_profile_streak'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='token',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
