# Generated by Django 4.1.1 on 2022-09-23 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_community_nomem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='communities',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='interest',
        ),
        migrations.AddField(
            model_name='profile',
            name='communities1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='communities2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='communities3',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='interest1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='interest2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='interest3',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
