# Generated by Django 4.1.1 on 2022-09-23 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_remove_profile_communities_remove_profile_interest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pp',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
