# Generated by Django 4.1.1 on 2022-09-23 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_alter_profile_pp'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='activeChat1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='activeChat2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='comChat1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='comChat2',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
