# Generated by Django 4.1.1 on 2022-09-23 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_profile_activechat1_profile_activechat2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bday',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
